"""
test_standard_dqn_e2e.py
-------------------------
End-to-End System Integration Test for Standard DQN Baseline:
  Test 1 - Login & Authentication
  Test 2 - Resume & Skill Gap Analysis
  Test 3 - RL Environment & Standard DQN Recommendation
  Test 4 - Learning & Video Completion Tracking
  Test 5 - 15-Question Quiz Generation & Submission
  Test 6 - Adaptive Difficulty & Standard DQN Feedback Loop
  Test 7 - Session Persistence & State Restoration
"""

import sys
import requests
import json

if sys.platform == "win32":
    try:
        sys.stdout.reconfigure(encoding="utf-8")
        sys.stderr.reconfigure(encoding="utf-8")
    except Exception:
        pass

BASE_URL = "http://localhost:8000"

def run_e2e():
    print("==========================================================")
    print("SKILLPATH AI: STANDARD DQN BASELINE END-TO-END SUITE")
    print("==========================================================")

    # ── Test 1 — Login / Account Ensure ──
    print("\n--- TEST 1: User Login & Session Token ---")
    # Register user if not already present
    requests.post(f"{BASE_URL}/auth/register", json={
        "username": "deepikadharanikota",
        "email": "deepika@skillpath.ai",
        "password": "password123",
        "target_role": "AI/ML Engineer"
    })
    login_resp = requests.post(f"{BASE_URL}/auth/local-login", json={"username": "deepikadharanikota", "password": "password123"})
    assert login_resp.status_code == 200, f"Login failed: {login_resp.text}"
    token = login_resp.json().get("token")
    headers = {"token": token, "Authorization": f"Bearer {token}"}
    me_resp = requests.get(f"{BASE_URL}/auth/me", headers=headers)
    assert me_resp.status_code == 200
    user_info = me_resp.json()["user"]
    print(f"✓ Real User Authenticated: {user_info['username']} (Email: {user_info.get('email')}, Role: {user_info.get('target_role')})")

    # ── Test 2 — Resume & Skill Gap Analysis ──
    print("\n--- TEST 2: Resume & Skill Gap Analysis ---")
    role_update = requests.put(f"{BASE_URL}/resume/target-role", json={"target_role": "AI/ML Engineer"}, headers=headers)
    assert role_update.status_code == 200
    gap_resp = requests.get(f"{BASE_URL}/resume/skill-gap", headers=headers)
    assert gap_resp.status_code == 200
    gap_data = gap_resp.json()
    print(f"✓ Target Role: AI/ML Engineer | Match: {gap_data.get('match_percentage')}% | Mastered: {len(gap_data.get('already_have', []))} | Missing: {len(gap_data.get('missing', []))}")

    # ── Test 3 — RL Agent Status & Recommendation ──
    print("\n--- TEST 3: Standard DQN Agent & Recommendation ---")
    agent_status_resp = requests.get(f"{BASE_URL}/learning/agent-status")
    assert agent_status_resp.status_code == 200
    agent_status = agent_status_resp.json()
    print(f"✓ RL Architecture: {agent_status['algorithm']} (Version: {agent_status['algorithm_version']})")
    print(f"✓ State Dim: {agent_status['state_dim']} | Action Dim: {agent_status['action_dim']} | Epsilon: {agent_status['epsilon']} | Trained Steps: {agent_status['train_steps']}")
    print(f"✓ Replay Type: {agent_status.get('replay_buffer_type', 'Uniform')}")
    assert agent_status["algorithm"] == "Standard DQN"
    assert agent_status["algorithm_version"] == "Standard-DQN-v1"

    rec_resp = requests.get(f"{BASE_URL}/dashboard/recommendations", headers=headers)
    assert rec_resp.status_code == 200
    recs = rec_resp.json()["recommendations"]
    print(f"✓ Dashboard Recommendations: {len(recs)} topics generated by Standard DQN engine.")
    print(f"  Top recommended topic: {recs[0]['topic']} (Difficulty: {recs[0].get('difficulty')}, Strategy: {recs[0].get('strategy')})")

    # ── Test 4 — Learning & Video Completion ──
    print("\n--- TEST 4: Video Learning & Progression Gating ---")
    vid_resp = requests.post(f"{BASE_URL}/learning/video/complete", json={
        "topic": "Machine Learning",
        "module": "intro",
        "video_id": "ml_intro_v1"
    }, headers=headers)
    assert vid_resp.status_code == 200
    vid_data = vid_resp.json()
    print(f"✓ Video marked complete. Module progress saved. Quiz unlocked: {vid_data.get('is_quiz_unlocked')}")

    # ── Test 5 — 15-Question Quiz System ──
    print("\n--- TEST 5: 15-Question Quiz System ---")
    quiz_resp = requests.get(f"{BASE_URL}/quiz/generate?topic=Machine%20Learning&module=intro", headers=headers)
    assert quiz_resp.status_code == 200
    quiz_data = quiz_resp.json()
    questions = quiz_data.get("questions", [])
    print(f"✓ Quiz Generated: Exactly {len(questions)} questions (Target: 15)")
    assert len(questions) == 15, f"Expected 15 questions, got {len(questions)}"
    for q in questions:
        assert len(q["options"]) >= 2
    
    quiz_id = quiz_data["quiz_id"]
    answers = {str(i): questions[i]["options"][0] for i in range(12)}
    answers["12"] = "__UNANSWERED__"
    answers["13"] = "__UNANSWERED__"
    answers["14"] = "__UNANSWERED__"

    sub_resp = requests.post(f"{BASE_URL}/quiz/submit", json={
        "quiz_id": quiz_id,
        "topic": "Machine Learning",
        "module": "intro",
        "answers": answers
    }, headers=headers)
    assert sub_resp.status_code == 200
    sub_data = sub_resp.json()
    print(f"✓ Quiz Submitted: Score={sub_data['score']}/15, Correct={sub_data['correct_count']}, Incorrect={sub_data['incorrect_count']}, Unanswered={sub_data['unanswered_count']}")
    print(f"✓ Adaptive Feedback: {sub_data['adaptive_feedback']}")
    print(f"✓ Next Difficulty: {sub_data['next_difficulty']}")
    assert sub_data["total_questions"] == 15
    assert sub_data["unanswered_count"] == 3

    # ── Test 6 — Adaptive Learning & RL Feedback Loop ──
    print("\n--- TEST 6: Standard DQN RL Feedback & Submit Module Transition ---")
    mod_resp = requests.post(f"{BASE_URL}/learning/submit_module", json={
        "quiz_score": sub_data["percentage"],
        "code_score": 85.0
    }, headers=headers)
    assert mod_resp.status_code == 200
    mod_data = mod_resp.json()
    print(f"✓ RL Environment Reward computed: {mod_data['reward']:+.4f}")
    next_rec = mod_data["next_recommendation"]
    print(f"✓ Standard DQN Next Recommendation: Topic={next_rec['topic']}, Difficulty={next_rec['difficulty']}, Action={next_rec.get('action')}")
    assert len(next_rec["q_values"]) == 27, f"Expected 27 action Q-values, got {len(next_rec['q_values'])}"
    assert len(next_rec["state"]) == 13, f"Expected 13 state dimensions, got {len(next_rec['state'])}"

    # ── Test 7 — Persistence Across Re-Login ──
    print("\n--- TEST 7: Persistence Across Sessions ---")
    relogin_resp = requests.post(f"{BASE_URL}/auth/local-login", json={"username": "deepikadharanikota", "password": "password123"})
    assert relogin_resp.status_code == 200
    new_token = relogin_resp.json().get("token")
    new_headers = {"token": new_token, "Authorization": f"Bearer {new_token}"}
    state_resp = requests.get(f"{BASE_URL}/learning/state", headers=new_headers)
    assert state_resp.status_code == 200
    restored_state = state_resp.json()
    print(f"✓ Learning state restored: Current Topic={restored_state.get('current_topic')}, Current Module={restored_state.get('current_module')}, Streak={restored_state.get('current_streak')}")
    
    print("\n==========================================================")
    print("ALL 7 END-TO-END INTEGRATION TESTS PASSED WITH 100% SUCCESS!")
    print("==========================================================")

if __name__ == "__main__":
    run_e2e()
